### ISSUE TITLE
🚀 [Illustration] - Yaay

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#32]
### Link of the Illustration

https://www.ls.graphics/illustrations/yaay

### Category of The Illustration

Paid

### Formats Available

Format
- Sketch
- Adobe Illustrator
- Adobe Xd
- Figma
- SVG
- Affinity

### Author

LS Graphics

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/blob/main/CONTRIBUTING.md) of this project.

**Comment by at-the-vr** [comment]
Hey Anmol, can i take this Issue as well

**Comment by Anmol-Baranwal** [comment]
I have assigned the issue to you. Read the contributing guidelines for sure.
