### ISSUE TITLE
🚀 [Illustration] - Ding

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#33]
### Link of the Illustration

https://www.ls.graphics/illustrations/ding

### Formats Available

Format
- Sketch
- Adobe Illustrator
- Adobe Xd
- Figma
- SVG
- Affinity

### Author

LS Graphics

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/blob/main/CONTRIBUTING.md) of this project.

**Comment by at-the-vr** [comment]
Hey Anmol, i see this is a Paid category illustration, can i take on this Issue ?
