### ISSUE TITLE
🚀 [Illustration] - Clusck 2.0

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#37]
### Link of the Illustration

https://www.ls.graphics/illustrations/clusck-2-0-illustration-kit

### Category of The Illustration

Paid

### Formats Available

Format
- Sketch
- Adobe Illustrator
- Adobe Xd
- Figma
- SVG
- Affinity
- PNG

### Author

LS Graphics

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/blob/main/CONTRIBUTING.md) of this project.

**Comment by at-the-vr** [comment]
Hi Anmol, can I start on with this Issue ?

**Comment by Anmol-Baranwal** [comment]
> Hi Anmol, can I start on with this Issue ?

Sure, go ahead. Every contribution is appreciated.

**Comment by at-the-vr** [comment]
Hey Anmol can i know how you upload the screenshots of your illustrations inside your README ? I dont think copying screenshot works here

**Comment by Anmol-Baranwal** [comment]
> Read the guidelines [here](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects#-how-to-contribute-).

- As stated, just drag the screenshot in your readme when you are editing and use the 
https://user-images.githubusercontent.com/...  link for your contribution. 
- You can use this link in the src attribute as: <img src="the_link"

**Comment by at-the-vr** [comment]
Hi Anmol, can you visit this [branch ](https://github.com/PiseAtharva/Awesome-Illustrations-4Projects/tree/development)and assess the changes 
![image](https://user-images.githubusercontent.com/88548999/217843185-0d68bb6f-2ca7-4514-8fdb-750826a48bcd.png) ![image](https://user-images.githubusercontent.com/88548999/217843039-e92ec324-1fbe-46e1-9b8f-f1aabe072170.png) 

If  all's good then I will start by raising a PR

**Comment by Anmol-Baranwal** [comment]
Raise PR, if any changes would be required. I will ask you for the same. 

Don't worry, i will review the code once the PR has been done.
