### ISSUE TITLE
🚀 150+ Vectors and Illustrations - Icons8.com

### ISSUE THREAD

**Issue by prathamcoral** [Anmol-Baranwal/Awesome-Illustrations-4Projects#45]
### Link of the Illustration

https://icons8.com/illustrations

### Category of The Illustration

Freemium

### Formats Available

Format
-  SVG
-  PNG

### Author

![image](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/assets/132425129/a278fded-ef90-4095-a0d4-0820a581076d)

https://icons8.com/illustrations

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/blob/main/CONTRIBUTING.md) of this project.

**Comment by Anmol-Baranwal** [comment]
Hello there!👋 Welcome to the project!🚀 Thank you and congrats🎉 for opening your very first issue in this project.
