### ISSUE TITLE
Chubbs

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#7]
# Illustration Information

Chubbs | `https://growwwkit.com/illustrations/chubbs/` | `Free`

## Optional Info

Formats Available - `AI`, `EPS`, `PNG`, `PDF`,  `Sketch`, `Corel Draw`. 

Author - `growwwkit`

**Comment by PrinceX04** [comment]
I want to work on this issue. Assign me

**Comment by Anmol-Baranwal** [comment]
@PrinceX04  This issue has already been covered and thus I am closing it. You can work on other issues.
